# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Lauren Ashley | Lifestyle, Travel, Rituals"
description: > # this means to ignore newlines until "email:"
   a little bit of everything

email: lor.ashley@gmail.com
#blog logo
logo: "/assets/images/logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Lauren Ramgattie'
author: 'Lauren Ramgattie'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://lorashley.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@LorTheCreator'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/LorTheCreator
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/lorashley
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
    
  - icon:	instagram
    url:	https://instagram.com/pawsandwander
    desc:	Follow me on IG
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
